export const routes = ['Op shop','Vinted','Marketplace','Council pickup','Bin / recycle'] as const;
export const stages:Record<string,string[]>={ 'Op shop':['Sorted','Bagged','Left house'],Vinted:['Found','Photograph','List','Sold','Post','Gone'],Marketplace:['Found','Photograph','List','Enquiry','Sold','Collected'],'Council pickup':['Identified','Ready outside','Collection booked','Collected'],'Bin / recycle':['Sorted','Ready','Left house']};
export type Photo={id:string;url:string;name:string};
export type Area={id:string;name:string;status:number;duration:number;priority:number;daily:boolean;notes:string;photos:Photo[];x:number;y:number};
export type Task={id:string;name:string;room:string;area:string;duration:number;priority:number;date:string;notes:string;done:boolean;photos:Photo[]};
export type Room={id:string;name:string;hero:string;after:string;photos:Photo[];notes:string;areas:Area[]};
export type Item={id:string;name:string;room:string;area:string;destination:string;status:string;left:boolean;quantity:number;bag:string;price:string;salePrice:string;suggestedPrice:string;size:string;brand:string;dimensions:string;notes:string;collection:string;photos:Photo[]};
export type State={move:{date:string;packingDate:string;current:string;next:string};rooms:Room[];items:Item[];tasks:Task[];essentials:{id:string;name:string;collection:string;done:boolean}[];council:{date:string;reference:string;location:string;notes:string};example:boolean};
export const uid=()=>crypto.randomUUID();
export function newItem(destination:string,room='',area=''):Item{return {id:uid(),name:'',room,area,destination,status:stages[destination][0],left:false,quantity:1,bag:'',price:'',salePrice:'',suggestedPrice:'',size:'',brand:'',dimensions:'',notes:'',collection:'',photos:[]}}
export function seed():State{const names=[['Living room','Bookcase','Sideboard','Decor','TV unit'],['Kitchen','Pantry','Drawers','Under sink','Cookware'],['Master bedroom','Wardrobe','Bedside drawers','Under bed','Shoes'],['Bathroom','Vanity','Cabinet','Toiletries'],['Office','Paperwork','Desk','Cables'],['Outdoor','Storage','Pots','Furniture']]; const rooms=names.map(([name,...areas],r)=>({id:`room-${r}`,name,hero:r===2?'/bedroom-3.jpg':'',after:'',photos:r===2?[{id:'before-1',url:'/bedroom-1.jpg',name:'Before · bedside'},{id:'before-2',url:'/bedroom-2.jpg',name:'Before · drawers'},{id:'before-3',url:'/bedroom-3.jpg',name:'Before · room'}]:[],notes:'',areas:areas.map((name,a)=>({id:`area-${r}-${a}`,name,status:r===0?2:r===1&&a===1?2:0,duration:[20,10,15,25][a%4],priority:a===0?3:2,daily:name==='Toiletries'||name==='Cookware',notes:'',photos:[],x:22+(a%2)*48,y:28+Math.floor(a/2)*38}))}));const records=[['Linen trousers','Vinted','List','room-2'],['Side table','Marketplace','Enquiry','room-0'],['Unworn knitwear','Op shop','Bagged','room-2'],['Spare mugs','Op shop','Sorted','room-1'],['Old shelving','Council pickup','Identified','room-5'],['Empty bottles','Bin / recycle','Left house','room-3']];return {move:{date:'2026-10-12',packingDate:'',current:'My current home',next:'My next chapter'},rooms,items:records.map(([name,destination,status,room],i)=>({...newItem(destination,room),id:`sample-${i}`,name,status,left:status==='Left house',bag:i===2?'Bag 01':'',quantity:i===2?4:i===3?3:1,price:i===0?'35':i===1?'60':'',notes:i===1?'Solid wood, good condition.':'',dimensions:i===1?'45 × 45 × 50 cm':''})),tasks:[{id:'task-1',name:'Photograph the Vinted pile',room:'room-2',area:'',duration:15,priority:3,date:'',notes:'Use daylight near the window.',done:false,photos:[]}],essentials:[...['Documents','Keys & wallet','Laptop & chargers','Valuables','Medications','Moving documents','Daily toiletries','Dog essentials'].map((name,i)=>({id:`dnp-${i}`,name,collection:'Do not pack',done:false})),...['Bedding','Towels','Kettle & mugs','First breakfast','Change of clothes'].map((name,i)=>({id:`fn-${i}`,name,collection:'First night',done:false}))],council:{date:'',reference:'',location:'',notes:''},example:true}}
export function metrics(s:State){const a=s.rooms.flatMap(r=>r.areas),out=s.items.reduce((n,i)=>n+i.quantity,0),gone=s.items.filter(i=>i.left).reduce((n,i)=>n+i.quantity,0);return {sorted:a.length?Math.round(a.filter(a=>a.status===2).length/a.length*100):0,cleared:out?Math.round(gone/out*100):0,out,gone,remaining:out-gone,ready:s.rooms.filter(r=>r.areas.length&&r.areas.every(a=>a.status===2)).length}}
export function daysTo(date:string){const now=new Date();const today=new Date(now.getFullYear(),now.getMonth(),now.getDate());return Math.ceil((new Date(date+'T00:00:00').getTime()-today.getTime())/86400000)}
export function plan(s:State,budget=60){const days=daysTo(s.move.packingDate||s.move.date);let candidates:any[]=[];s.rooms.forEach(r=>r.areas.filter(a=>a.status!==2).forEach(a=>{const remaining=r.areas.filter(x=>x.status!==2).length/r.areas.length;candidates.push({id:a.id,kind:'area',name:a.name,room:r.id,subtitle:r.name,duration:a.duration,score:a.priority*10+(a.status===1?30:0)+(a.daily?(days>2?-35:35):15)+remaining*10+(days<4?15:0)})}));s.tasks.filter(t=>!t.done).forEach(t=>candidates.push({...t,kind:'task',subtitle:s.rooms.find(r=>r.id===t.room)?.name||'House',score:t.priority*10+(t.date&&daysTo(t.date)<=1?60:0)}));routes.forEach(d=>{const items=s.items.filter(i=>i.destination===d&&!i.left);if(items.length)candidates.push({id:d,kind:'out',name:d==='Op shop'?'Take the donation pile':d==='Vinted'?'Move your Vinted pile forward':d==='Marketplace'?'Follow up listings & collection':d==='Council pickup'?'Arrange council collection':'Take out recycling',subtitle:`${items.reduce((n,i)=>n+i.quantity,0)} items still here`,duration:d==='Op shop'?25:10,score:25+items.length*4+(days<4?40:0)+(d==='Council pickup'&&s.council.date&&daysTo(s.council.date)<=1?60:0)})});candidates.sort((a,b)=>b.score-a.score||a.duration-b.duration);const chosen=[];let left=budget;for(const c of candidates){if(c.duration<=left){chosen.push(c);left-=c.duration}if(chosen.length===3)break}return chosen}
